/object_locator:
  ros__parameters:
    act_on: "brightness"
    history: "keep-last"
    depth: "1"
    brightness_threshold: "100"
    red_threshold: "0"
    blue_threshold: "0"
    green_threshold: "200"
