/brightness_calculator:
  ros__parameters:
    threshold: 50
    history: "keep_last"
    durability: "volatile"
    reliability: "reliable"
    publish_mode: "continuous"
    show_camera: true

    depth: 10