/brightness_calculator:
  ros__parameters:
    history: "keep_last"
    depth: 1
    durability: "volatile"
    reliability: "reliable"
    threshold: 20
    image_source_topic: "/output/moving_camera"
    