/brightness_calculator:
  ros__parameters:
    threshold: 20
    history: "keep_last"
    durability: "volatile"
    reliability: "reliable"
    publish_mode: "continuous"
    show_camera: true
    depth: 1